experiment_name: cities_test_defender_5
cities: test_city_list
num_defenders: 5 #NOTE: This is the max number of defenders
adr_ratio: 1
attacker_payload: 4 #NOTE: This is the max payload of the attacker.
attacker_batteries: [6]
num_samples: 100
parallelize: True # True, False
reward_scale_factor: 3 #1 = one-to-one, 2 = 2^X, 3 = 10^X
perturb_rewards: 0 #this is the percentage of the reward that is perturbed